### ISSUE TITLE
Example Missing

### ISSUE THREAD

**Issue by Malkiat-Singh** [MaximilianBuegler/node-kinetics#1]
Hi 
I want to use this in my ionic 2 app. But due to lack of example I am unable to do. 
Please share example code if possible

Thanks

**Comment by MaximilianBuegler** [comment]
Hi,

the readme provides an example for each function. Furthermore the test 
directory provides more examples. What kind of example would you like? 
I'd be happy to help.

Kind regards

Max

**Comment by MaximilianBuegler** [comment]
I added more examples to the readme and added clearer descriptions. I hope it helps,

**Comment by Malkiat-Singh** [comment]
will check very soon
